# Generated by Django 5.0.9 on 2026-08-15 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('weight_class', models.CharField(db_index=True, max_length=50)),
                ('stance', models.CharField(blank=True, max_length=10)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('knockouts', models.PositiveIntegerField(default=0)),
                ('ranking', models.PositiveSmallIntegerField(blank=True, help_text='Rank within weight_class, if any', null=True)),
                ('is_p4p', models.BooleanField(default=False)),
                ('profile_image_key', models.CharField(blank=True, max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fighter_listing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['weight_class', 'ranking'], name='fighters_fi_weight__3ec239_idx')],
            },
        ),
    ]
