# Generated by Django 5.0.9 on 2026-08-15 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('fights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('video_type', models.CharField(choices=[('HIGHLIGHT', 'Highlight'), ('FULL_REPLAY', 'Full replay'), ('INTERVIEW', 'Interview'), ('PRESS_CONFERENCE', 'Press conference')], default='HIGHLIGHT', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('playback_url', models.URLField(blank=True)),
                ('requires_subscription', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='events.event')),
                ('fight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='fights.fight')),
            ],
            options={
                'indexes': [models.Index(fields=['video_type'], name='videos_vide_video_t_2e9eac_idx')],
            },
        ),
    ]
