# Generated by Django 5.2.17 on 2026-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete (awaiting first payment)'), ('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='INCOMPLETE', max_length=15),
        ),
    ]
