# Generated by Django 5.0.9 on 2026-08-15 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('WARN', 'Warning'), ('MUTE', 'Chat mute'), ('SUSPEND', 'Account suspension'), ('BAN', 'Account ban'), ('CONTENT_REMOVED', 'Content removed')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['target_user', 'action_type'], name='moderation__target__1dad74_idx')],
            },
        ),
    ]
