# Generated by Django 5.2.17 on 2026-08-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxerprofile',
            name='highlight_video_url',
            field=models.URLField(blank=True),
        ),
    ]
