# Generated by Django 5.0.9 on 2026-08-15 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('source_type', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('FEDERATION', 'Boxing federation'), ('PROMOTER', 'Promoter'), ('BROADCASTER', 'Free broadcaster'), ('EVENT_WEBSITE', 'Official event website'), ('SOCIAL', 'Official social livestream')], max_length=20)),
                ('tier', models.CharField(choices=[('TIER1_OFFICIAL', 'Tier 1 — Official'), ('TIER2_AUTHORIZED', 'Tier 2 — Authorized partner'), ('TIER3_PUBLIC', 'Tier 3 — Public legitimate broadcast')], default='TIER3_PUBLIC', max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('adapter_class', models.CharField(max_length=255)),
                ('embeddable', models.BooleanField(default=False, help_text="Source's terms permit embedding their player")),
                ('enabled', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False, help_text="Only verified sources' events are shown to users (spec §5).")),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dedup_key', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('promotion', models.CharField(blank=True, max_length=150)),
                ('fighter_1', models.CharField(max_length=150)),
                ('fighter_2', models.CharField(max_length=150)),
                ('weight_class', models.CharField(blank=True, max_length=50)),
                ('event_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('UNAVAILABLE', 'Unavailable')], default='UPCOMING', max_length=15)),
                ('is_free', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['dedup_key'], name='streams_liv_dedup_k_7e93e9_idx'), models.Index(fields=['status', 'start_time'], name='streams_liv_status_ea2550_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveEventStream',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField()),
                ('embed_url', models.URLField(blank=True)),
                ('is_embeddable', models.BooleanField(default=False)),
                ('requires_subscription', models.BooleanField(default=False)),
                ('requires_ppv', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='streams.liveevent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='streams.streamsource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='liveeventstream',
            constraint=models.UniqueConstraint(fields=('event', 'source', 'source_url'), name='uniq_event_source_url'),
        ),
    ]
