# Generated by Django 5.0.9 on 2026-08-15 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('fighters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_class', models.CharField(blank=True, max_length=50)),
                ('is_title_fight', models.BooleanField(default=False)),
                ('card_position', models.PositiveSmallIntegerField(default=0, help_text='0 = main event')),
                ('rounds_scheduled', models.PositiveSmallIntegerField(default=12)),
                ('result_method', models.CharField(blank=True, choices=[('KO', 'Knockout'), ('TKO', 'Technical knockout'), ('DECISION', 'Decision'), ('DRAW', 'Draw'), ('NO_CONTEST', 'No contest'), ('DQ', 'Disqualification')], max_length=20)),
                ('result_round', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='events.event')),
                ('fighter_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fights_as_fighter_1', to='fighters.fighter')),
                ('fighter_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fights_as_fighter_2', to='fighters.fighter')),
                ('result_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_results_recorded', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fights_won', to='fighters.fighter')),
            ],
            options={
                'ordering': ['card_position'],
            },
        ),
    ]
